apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-apps
  namespace: argocd # Namespace where ArgoCD is installed
spec:
  destination:
    namespace: nginx-namespace # Target namespace for deployment
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/amahmoodi181188/k8s-configs.git
    targetRevision: HEAD
    path: ./manifests
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
