apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-apps
  namespace: argocd # Namespace where ArgoCD is installed
spec:
  destination:
    namespace: nginx-namespace # Default namespace for deployment
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/amahmoodi181188/k8s-configs.git
    targetRevision: HEAD
    path: ./manifests # Directory containing Kubernetes manifests
  project: default
  syncPolicy:
    automated:
      prune: true # Automatically prune resources that are no longer in Git
      selfHeal: true # Automatically sync if drift is detected
