apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-nginx-to-app1
  namespace: app1-namespace
spec:
  podSelector:
    matchLabels:
      app: app1
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            app: nginx
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-nginx-to-app2
  namespace: app2-namespace
spec:
  podSelector:
    matchLabels:
      app: app2
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            app: nginx