# Allow Nginx to communicate with app1 in app1-namespace
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-nginx-namespace
  namespace: app1-namespace
spec:
  podSelector:
    matchLabels:
      app: app1
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: nginx-namespace # Allow Nginx pods to access app1
  egress:
    - to:
        - podSelector:
            matchLabels:
              k8s-app: kube-dns # Allow outgoing DNS queries
          namespaceSelector:
            matchLabels:
              name: kube-system
        - namespaceSelector:
            matchLabels:
              name: nginx-namespace # Allow responses to Nginx pods
      ports:
        - protocol: TCP
          port: 80
        - protocol: UDP
          port: 53 # DNS
        - protocol: TCP
          port: 53 # DNS
---
# Allow Nginx to communicate with app2 in app2-namespace
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-nginx-namespace
  namespace: app2-namespace
spec:
  podSelector:
    matchLabels:
      app: app2
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: nginx-namespace # Allow Nginx pods to access app2
  egress:
    - to:
        - podSelector:
            matchLabels:
              k8s-app: kube-dns # Allow outgoing DNS queries
          namespaceSelector:
            matchLabels:
              name: kube-system
        - namespaceSelector:
            matchLabels:
              name: nginx-namespace # Allow responses to Nginx pods
      ports:
        - protocol: TCP
          port: 80
        - protocol: UDP
          port: 53 # DNS
        - protocol: TCP
          port: 53 # DNS
