apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-nginx-to-app1
  namespace: app1-namespace
spec:
  podSelector:
    matchLabels:
      app: app1 # Adjust this to match the labels for your app1 Pods
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: nginx-namespace # Allow traffic from default namespace
          podSelector:
            matchLabels:
              app: nginx # Allow traffic only from Nginx Pods in default namespace
      ports:
        - protocol: TCP
          port: 8080 # Allow HTTP traffic from Nginx
  egress:
    - to:
        - ipBlock:
            cidr: 34.0.0.0/8 # Allow access to Kubernetes DNS service
      ports:
        - protocol: UDP
          port: 53 # DNS resolution
        - protocol: TCP
          port: 53
    - to:
        - namespaceSelector:
            matchLabels:
              name: nginx-namespace
          podSelector:
            matchLabels:
              app: nginx # Allow traffic only to Nginx Pods in default namespace
      ports:
        - protocol: TCP
          port: 80
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-nginx-to-app2
  namespace: app2-namespace
spec:
  podSelector:
    matchLabels:
      app: app2 # Adjust this to match the labels for your app2 Pods
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: nginx-namespace # Allow traffic from default namespace
          podSelector:
            matchLabels:
              app: nginx # Allow traffic only from Nginx Pods in default namespace
      ports:
        - protocol: TCP
          port: 8080 # Allow HTTP traffic from Nginx
  egress:
    - to:
        - ipBlock:
            cidr: 34.0.0.0/8 # Allow access to Kubernetes DNS service
      ports:
        - protocol: UDP
          port: 53 # DNS resolution
        - protocol: TCP
          port: 53
    - to:
        - namespaceSelector:
            matchLabels:
              name: nginx-namespace
          podSelector:
            matchLabels:
              app: nginx # Allow traffic only to Nginx Pods in default namespace
      ports:
        - protocol: TCP
          port: 80