apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: app1-namespace
  name: app1-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: app1-namespace
  name: app1-role-binding
subjects:
  - kind: ServiceAccount
    name: app1-sa
    namespace: app1-namespace
roleRef:
  kind: Role
  name: app1-role
  apiGroup: rbac.authorization.k8s.io
