apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: app2-namespace
  name: app2-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: app2-namespace
  name: app2-role-binding
subjects:
  - kind: ServiceAccount
    name: app2-sa
    namespace: app2-namespace
roleRef:
  kind: Role
  name: app2-role
  apiGroup: rbac.authorization.k8s.io
