apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
data:
  nginx.conf: |
    events {}
    http {
        upstream backend {
            server app1:8080 weight=1; # 20% traffic
            server app2:8080 weight=4; # 80% traffic
        }

        server {
            listen 80;

            location / {
                proxy_pass http://backend;
            }
        }
    }
