apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: nginx-namespace
data:
  nginx.conf: |
    events {}
    http {
        upstream backend {
            server app1.app1-namespace.svc.cluster.local:80 weight=1; # 20% traffic
            server app2.app2-namespace.svc.cluster.local:80 weight=4; # 80% traffic
        }

        server {
            listen 80;

            location / {
                proxy_pass http://backend;
            }
        }
    }
