apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-nginx
  namespace: nginx-namespace
spec:
  podSelector:
    matchLabels:
      app: nginx
  ingress:
    - from:
        - ipBlock:
            cidr: 0.0.0.0/0 # Allow traffic from anywhere to Nginx
      ports:
        - protocol: TCP
          port: 80
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              name: app1-namespace
          podSelector: {}
      ports:
        - protocol: TCP
          port: 8080
    - to:
        - namespaceSelector:
            matchLabels:
              name: app2-namespace
          podSelector: {}
      ports:
        - protocol: TCP
          port: 8080
