apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nginx-network-policy
  namespace: nginx-namespace
spec:
  podSelector:
    matchLabels:
      app: nginx
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - ipBlock:
            cidr: 0.0.0.0/0 # Allow external traffic
      ports:
        - protocol: TCP
          port: 80 # Allow HTTP traffic to Nginx
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              name: app1-namespace # Allow traffic to app1's namespace
          podSelector:
            matchLabels:
              app: app1 # Allow traffic to app1 Pods
      ports:
        - protocol: TCP
          port: 8080
    - to:
        - namespaceSelector:
            matchLabels:
              name: app2-namespace # Allow traffic to app2's namespace
          podSelector:
            matchLabels:
              app: app2 # Allow traffic to app2 Pods
      ports:
        - protocol: TCP
          port: 8080
    - to:
        - ipBlock:
            cidr: 34.0.0.0/8 # Allow DNS traffic
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53