# nginx-network-policy.yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nginx-allow-lb
  namespace: default
spec:
  podSelector: {}
  ingress:
    - {} # Allow all incoming traffic
  egress:
    - {} # Allow all outgoing traffic
