apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: go-apps
spec:
  hosts:
  - "*"
  gateways:
  - go-apps-gateway
  http:
  - route:
    - destination:
        host: app2-service
        port:
          number: 80
      weight: 80
    - destination:
        host: app1-service
        port:
          number: 80
      weight: 20
